{% set name = "extensisq" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/extensisq-{{ version }}.tar.gz
  sha256: 54791a0f60ec007a1bd1c50588b8cb3f47495619ffa0deeba38c990cdd212cd7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.4.0
    - python >=3.6
    - scipy >=1.0.0

test:
  imports:
    - extensisq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WRKampi/extensisq
  summary: Extend scipy.integrate with various methods for solve_ivp
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WRKampi
